### ISSUE TITLE
newfs_udf fails with USB3 Flash drive on OS X

### ISSUE THREAD

**Issue by ler0ck** [JElchison/format-udf#17]
I'm on Mac (in fact hackintosh and macbook air) and I succeed to format a first USB flash drive and a internal hard drive in UDF, they were both USB2. But the process fails with a USB3 flash drive. I don't know why. 
https://www.7dayshop.com/products/grixx-usb-3-0-flash-drive-90m-s-64gb-WH2-GRUSB64GBALUU3
This is a copy text of the terminal :
``` 
The above-listed drive (and partitions, if any) will be completely erased.
Type 'yes' if this is what you intend:  yes
[+] Detecting total size...
[*] Using total size of 62440340992
[+] Validating detected total size...
[+] Detecting physical block size...
[*] Using block size of 512
[+] Validating detected block size...
[+] Unmounting drive...
Unmount of all volumes on disk7 was successful
[+] Zeroing out any existing partition table on drive...
4096+0 records in
4096+0 records out
2097152 bytes transferred in 1.334498 secs (1571491 bytes/sec)
[+] Formatting /dev/disk7 ...
write: Device not configured
[-] Format failed!
```

But otherwise it's working perfectly with USB2 devices on Linux, OS X and Windows ! Thanks for that !

**Comment by JElchison** [comment]
hi @ler0ck, thanks for the report!

sorry to hear that format-udf didn't work with USB3.  i'm moderately surprised by that, as the USB version should be abstracted away by the OS and drivers.  but nonetheless, let's dig in.

have you tried running the underlying UDF tools directly, without using format-udf as a wrapper?  to see what you might need to execute, you can add `set -x` to the top of format-udf to see how it's invoking `newfs_udf`.

are you able to attempt running format-udf on your USB3 flash drive, but from a different (Linux?)  machine?  i'm curious whether this is related to your OS and/or the version of the udftools.

alternatively, do you happen to have another USB3 device that you can validate this with?  i'm looking for multiple data points.  it's possible we're dealing with (yet) another issue with block sizes.

more debugging info that might be helpful:

* is the issue reproducible?
    * what are the exact environment/steps that i can use to reproduce it?
* does the issue still occur if you use a different USB3 flash drive?
* does the issue still occur if you use a USB3 hard drive?
* does the issue still occur if you use Linux to run format-udf, but with the same USB3 drive?
* does the issue still occur if you use OS X on a "real" mac to run format-udf?
* what version of udftools are you using?
* what version of format-udf are you using?

also, please post output from each of the following.  note, these are linux commands, so they may need to be translated into their OS X counterparts:

* the actual format-udf command you used
* ```uname -a```
* ```lsb_release -a```
* any relevant output from syslog
* `sudo fdisk -l`
    * is your drive in the list?
* `sudo blkid -c /dev/null /dev/sdX`, where X is the letter associated with your drive (or OS X equivalent)
* ```mount```

any additional info you could provide me would be really helpful.

also, please take a look through the other open [issues](https://github.com/JElchison/format-udf/issues) to see if anything there sounds like it might relate to your scenario.

thanks!

**Comment by ler0ck** [comment]
For now I just retried on a macbook air. 
It still doesn't work for my only usb3 key with these terminal commands : 
- diskutil info /dev/disk5 | grep "Block Size"      //I get 512
- sudo newfs_udf -b 512 /dev/disk5 

then I still have : 
write: Device not configured
[-] Format failed!

BUT it perfectly works with an internal HDD connected in USB3 by a disk enclosure.
So I think the key has a problem, I'll try to get another one and continue.
I will also test it on Linux and post the syslog !!!

**Comment by JElchison** [comment]
thanks for reporting back!

since you've had other success with USB3, this issue doesn't sound like a USB3 issue.  i'll rename the issue to something more generic.

i'm beginning to wonder if diskutil is reporting the wrong block size.  how large is your problematic USB3 drive?

are you willing to plug that USB3 drive back into a linux machine, and report the output from:
* `hdparm -I /dev/sdX`
* `smartctl -a /dev/sdX`

also, i'm sure you know already, but your manual invocations of the newfs_udf command should be of the following form:
```
newfs_udf -b $BLOCK_SIZE -m blk -t ow -r 2.01 -v "$LABEL" --enc utf8 /dev/$DEVICE
```

i'm curious what happens if you try a $BLOCK_SIZE of 1024, 2048, and 4096.  do any of those work?

thanks!

**Comment by JElchison** [comment]
Since we haven't heard from @ler0ck since the ticket was opened about 13 months ago, I feel comfortable closing this issue with the clarifying text I've just [added](https://github.com/JElchison/format-udf/blob/master/README.md#block-size) on the README.  Essentially, there's not much that format-udf can do if OS X has trouble auto-mounting drives with certain block sizes.

Related discussion is still welcome in this thread.  I'm always more that happy to revisit this issue if there's any way that format-udf can produce drives that are more compatible on target OSes (while respecting the device geometry, of course).

Additionally, note recent commentary on #16 for additional background.
