### ISSUE TITLE
Safe examples

### ISSUE THREAD

**Issue by antmak** [JElchison/format-udf#22]
I would like you to change text like "Example:  ./format-udf.sh sda "My External Drive" to avoid "sda" references :)

**Comment by JElchison** [comment]
Can do, good idea.

**Comment by JElchison** [comment]
Thanks for the quick PR!  Fixed with #23

**Comment by polarathene** [comment]
@JElchison why g? I guess it's reasonably safe to assume most systems would not have that many drives connected, I noticed the `sdg` in README example and thought it a bit odd. In most examples you'll see they seem to use `sdx`. I guess it doesn't make much of a worthwhile difference to change to that.

**Comment by JElchison** [comment]
Because that's what @antmak submitted in his pull request.  :)  https://github.com/JElchison/format-udf/pull/23/commits/d14064455e5df4368fb907fdf9a2c18fb211515b

You're welcome to submit another pull request if you want, but I agree:  it doesn't make much of a worthwhile difference to change to that.
