### ISSUE TITLE
Cannot set block size Advanced Format Drive.

### ISSUE THREAD

**Issue by schistkicker** [JElchison/format-udf#38]
Sorry if this question/topic has been solved before or if I'm just not smart enough to get the syntax right with the script, but I have not located a clear answer after hours of scouring...

I have a new Seagate 5TB drive that has the 4k (Advanced Format) architecture on it with 512 emulation (512e), fdisk -l shows "Units: sectors of 1 * 512 = 512 bytes" "Sector size (logical/physical): 512 bytes / 4096 bytes" "I-O size (minimum/optimal): 4096 bytes / 33553920 bytes".. I want to obviously use the entire 5TB drive when formatting udf and not limit the capacity to 2TB; however, using the -b flag spits out the arguments help output and the README doesn't seem to provide clear language about how to run this argument. I guess my main problem is figuring out how to properly syntax the command to run the tool and configure the drive properly. Can someone please help by clearly spelling out the command in a Linux system? Many thanks.

**Comment by JElchison** [comment]
Hi @schistkicker, welcome to GitHub!

If you require to use the full 5TB, then UDF is not for you.  Your device has a logical block size of 512 bytes, which means that your maximum UDF file system capacity is 2TiB.  There is no way around this.  Please read the entire [README](https://github.com/JElchison/format-udf/blob/master/README.md) for details.

The `-b BLOCK_SIZE` option is an expert-only option.  I recommend against using it, for reasons also detailed on the [README](https://github.com/JElchison/format-udf/blob/master/README.md).

If you're having a problem invoking the script, I'm happy to look at your syntax.  However, I don't think that you'll be pleased with the result.  The 2 TiB limitation is due to your choice of UDF, not the use of format-udf.

If you want to use the full 5TB, then I recommend selecting another format, such as NTFS.

**Comment by schistkicker** [comment]
Great, thank you @JElchison! I read everything in the README but this kind of stuff is not my everyday thing, so maybe some of what was said didn't come across clearly for someone like myself.

I'll format the disk to use NTFS and make everything simpler, thank you again!
