### ISSUE TITLE
Fake partition table for extra compatibility

### ISSUE THREAD

**Issue by IvanAnishchuk** [JElchison/format-udf#9]
How about creating a partition table with one partition, starting on the 0th sector? Like [this script](http://sipa.ulyssis.org/wp-content/uploads/2010/02/udfhd.pl_.txt). Also, [some comments](http://sipa.ulyssis.org/2010/02/filesystems-for-portable-disks/) on why is this needed might help.

I never personally tested my udf disk on all those systems, I only use linux, but it seems like a cool idea anyway.

**Comment by JElchison** [comment]
Hi @IvanAnishchuk, thanks for the message.  Turns out I'm already one step ahead of you.  :)  I've been aware of the Perl script you referenced for quite some time, but it doesn't behave consistently.  In the past week, I've reverse-engineered it and discovered some defects that may lead to inconsistent behavior.  I'm currently in the process of incorporating the goal of that Perl script into format-udf--for the best of both worlds.

Stay tuned!

See also #7 and [this page](https://github.com/JElchison/format-udf/wiki/Windows-has-trouble-recognizing-UDF-block-devices).

**Comment by JElchison** [comment]
Hi @IvanAnishchuk, just a heads up that version 1.1.0 of format-udf includes the fake MBR for added UDF compatibility on Windows.

Thanks for your interest!
